name: Build & Deploy (frontend)

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set image vars
        id: vars
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/hotel-web" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          build-args: |
            VITE_API_BASE=/api
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Bump GitOps manifests ---
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: mohamedmahtali/hotel-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops
          fetch-depth: 0

      - name: Update image in GitOps (frontend)
        working-directory: gitops
        run: |
          sed -i "s#\(image:\s*\)ghcr\.io/.*/hotel-web:.*#\1${{ env.IMAGE }}:${{ env.TAG }}#" prod-web.yaml

          git config --global user.email "bot@github-actions"
          git config --global user.name  "github-actions[bot]"
          git add prod-web.yaml
          git commit -m "ci(gitops): bump frontend image to ${{ env.IMAGE }}:${{ env.TAG }}" || echo "No changes to commit"
          git push
