name: Build & Deploy (backend)

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

permissions:
  contents: write     # push dans le repo GitOps
  packages: write     # push d'image vers GHCR

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set image vars
        id: vars
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/hotel-api" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Bump GitOps manifests ---
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: mohamedmahtali/hotel-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops
          fetch-depth: 0

      - name: Update image in GitOps (backend)
        working-directory: gitops
        run: |
          # remplace la ligne "image: ghcr.io/.../hotel-api:xxx"
          sed -i "s#\(image:\s*\)ghcr\.io/.*/hotel-api:.*#\1${{ env.IMAGE }}:${{ env.TAG }}#" prod-api.yaml

          git config user.email "bot@github-actions"
          git config user.name  "github-actions[bot]"
          git add prod-api.yaml
          git commit -m "ci(gitops): bump backend image to ${{ env.IMAGE }}:${{ env.TAG }}" || echo "No changes to commit"
          git push
